### ISSUE TITLE
Add command to suggest the changes that need to be done to CSPC

### ISSUE THREAD

**Issue by kmova** [openebs/openebsctl#84]
In cases, where a node is offline or gone out of the cluster and the disks from old (gone) node are moved to a new node in the cluster. Provide the user with an updated CSPC yaml with the required node selector change. 

This can be a follow-up activity or a correction action - once the cstor debug command has identified that there is a problem to a given CSPI.

**Comment by vharsh** [comment]
> Provide the user with an updated CSPC yaml with the required node selector change.

@kmova In my PR to close the issue I have patched the CSPC with the correct newNode name if the `newNode` is in Ready condition, should I just print the YAML so that the user can take a look or should the patch logic(magic magic) be a good approach.

**Comment by vharsh** [comment]
Would it be a good idea to check if the associated BDs **have actually moved to the newer node** and **are in active state**(i.e. NDM is on that node & has confirmed that the BD has actually moved), this might help save some confusion & time spent checking manually if the node has moved. If some BD is still not updated to newNode, the CLI can throw errors so that CStor CSI components don't need to throw errors.

**Comment by Abhinandan-Purkait** [comment]
cStor is deprecated and all the cli commands around that have also been deprecated.
